language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_SKIP=pp*
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND="nosetests {project}/tests"
    # - TWINE_USERNAME=joerick
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload --repository testpypi wheelhouse/*.whl
    fi
