environment:
  global:
    CIBW_SKIP: pp*
    CIBW_TEST_REQUIRES: nose
    CIBW_TEST_COMMAND: "nosetests {project}\\tests"
    TWINE_USERNAME: asfaltboy
    # Note: TWINE_PASSWORD is set in Appveyor settings

init:
- set PATH=C:\Python38;C:\Python38\Scripts;%PATH%

build_script:
  - python -m pip install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install --disable-pip-version-check twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
